### ISSUE TITLE
Option to return JSON response for search_url and search_data

### ISSUE THREAD

**Issue by johns1342** [TinEye/pytineye#6]
For the search_url and search_data methods in api.py, it would be great to have a way to get the JSON response or the dictionary back.  Right now it only returns a TinEyeResponse object which is not JSON serializable and felt a little counterintuitive when going from the the TinEye API documentation to pytineye.  I added a json_response=False parameter to each function locally and can submit a pull request if that seems like a good solution.

**Comment by tineyedev** [comment]
Hi @johns1342,

That's a good point, we ported this from our Python library originally and it returns an object. I think we'll just remove the `TinEyeResponse` object altogether in the next release. Thanks for your feedback!

**Comment by jgould22** [comment]
I realize this issue has been languishing for some time, my apologies.

During the time this was opened and now the HMAC authentication method has been deprecated and creating requests is now a lot easier. Instead of signing the requests you need now only include a header with an API key. You can read more about that [here](https://services.tineye.com/developers/tineyeapi/api_reference#search). 

In light of the above changes I think the recommendation is if the raw JSON values are what you desire you can make the request directly without the pytineye library.
